-- CreateEnum
CREATE TYPE "ReportType" AS ENUM ('CHAT_GPT_WAITING', 'CHAT_GPT_RUNNING', 'CHAT_GPT_COMPLETE', 'CUSTOM');

-- AlterTable
ALTER TABLE "Report" ADD COLUMN     "reportType" "ReportType" NOT NULL DEFAULT 'CHAT_GPT_WAITING',
ADD COLUMN     "restTime" INTEGER NOT NULL DEFAULT 0;
